#ifndef MAINWINDOW_H
#define MAINWINDOW_H

/*
    Main application window header.

    This file declares the MainWindow class which:
    - Acts as the GUI controller
    - Connects UI actions (buttons, menu items) to logic
    - Communicates with the file organizer backend
*/

// Organizer logic (core backend)
#include "organizer.hpp"

// Qt core GUI components
#include <QMainWindow>
#include <QMessageBox>
#include <QFileDialog>

// Qt concurrency utilities (for background threading)
#include <QtConcurrent>
#include <QFutureWatcher>

// Used to open folders in the system file explorer
#include <QDesktopServices>

/*
    Forward declaration of the UI class generated by Qt Designer.

    Qt creates a class named Ui::MainWindow automatically
    from the .ui file. We only keep a pointer to it here.
*/
QT_BEGIN_NAMESPACE
namespace Ui {
class MainWindow;
}
QT_END_NAMESPACE

/*
    MainWindow class:

    Responsibilities:
    - Display the GUI
    - React to user interactions (buttons, menu actions)
    - Start file organization in a background thread
    - Handle results and show messages to the user
*/
class MainWindow : public QMainWindow
{
    Q_OBJECT    // Required for Qt's signal-slot system

public:
    /*
        Constructor:
        - Initializes UI
        - Sets up connections
        - Applies default theme
    */
    MainWindow(QWidget *parent = nullptr);

    /*
        Destructor:
        - Cleans up dynamically allocated UI object
    */
    ~MainWindow();

private slots:
    /*
        Slot triggered when the "Organize" button is clicked.

        Starts the file organization process in a background thread.
    */
    void on_organize_button_clicked();

    /*
        Slot triggered when user selects the "Dark Theme" action
        from the menu.
    */
    void on_action_dark_theme_triggered();

    /*
        Slot triggered when user selects the "Light Theme" action
        from the menu.
    */
    void on_action_light_theme_triggered();

    /*
        Slot triggered when user selects the "About" action
        from the menu.
    */
    void on_action_about_triggered();

    /*
        Slot triggered when the "Browse" button is clicked.

        Opens a directory selection dialog and fills the path field.
    */
    void on_browse_button_clicked();

    /*
        Slot triggered when the "Clear" button is clicked.

        clears text of path field.
    */
    void on_clear_button_clicked();

private:
    /*
        Pointer to the UI elements generated from the .ui file.

        This contains all widgets like:
        - buttons
        - text fields
        - labels
        etc.
    */
    Ui::MainWindow *ui;

    /*
        Current file transfer mode used by the organizer.

        Default:
        - atomic_transfer_mode (fast rename-based move)

        Can be switched to fallback mode if cross-device error occurs.
    */
    transfer_mode current_mode = transfer_mode::atomic_transfer_mode;

    /*
        Applies a Qt stylesheet (.qss file) to the entire application.

        Declared static because:
        - It does not depend on instance-specific state
        - It modifies global application appearance
    */
    static void apply_theme(QString theme_path);

    /*
        Called automatically when the background organization task finishes.

        Reads the result from QFutureWatcher and:
        - Updates UI
        - Shows success or error messages
    */
    void on_organization_finished();

    /*
        QFutureWatcher monitors the background thread started
        using QtConcurrent::run().

        Purpose:
        - Safely retrieve result from worker thread
        - Notify GUI thread when work is complete
    */
    QFutureWatcher<organize_status> result_watcher;
};

#endif // MAINWINDOW_H
